version: '3'

services:
  mariadb:
    container_name: ALFRED
    build:
      context: ./
      dockerfile: Dockerfile

    env_file: 
      - ./.env

    volumes:
    - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    - ./mysql_data:/var/lib/mysql

    ports:
    - 3307:3307/tcp
