version: '3'

services:
  mariadb:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: 
      - /home/ubuntu/devops-skills-test/.env
    environment:
      BRUCE: ${BRUCE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    volumes:
    - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    - ./mysql_data:/var/lib/mysql
    ports:
    - 3307:3307/tcp
